export enum pokemonType_ES {
    FIRE = 'fuego',
    WATER = 'agua',
    GRASS = 'planta',
    NORMAL = 'fuego',
    DARK = 'siniestro',
    GHOST = 'fantasma',
    PSYCHIC = 'psíquico',
    FAIRY = 'hada',
    STEEL = 'acero',
    ROCK = 'roca',
    GROUND = 'tierra',
    POISON = 'veneno',
    DRAGON = 'dragón',
    BUG = 'bicho',
    FLYING = 'volador',
    FIGHTING = 'lucha',
    ELECTRIC = 'eléctrico',
    ICE = 'hielo',
}